# -*- coding: utf-8 -*-
"""inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/146yGxKFVDTipMlGooruYTkTHP2E1SfAJ
"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report
import joblib


# Load data
data = "https://raw.githubusercontent.com/AseLole112/Analisis_Berita_Hoaxs_dan_Fakta/master/data_clean.csv"


df = pd.read_csv(data, sep=';')
df[['final_text', 'label']] = df['final_text,label'].str.split(',', n=1, expand=True)
df = df.drop('final_text,label', axis=1)
df = df.dropna(subset=['final_text']).reset_index(drop=True)

# convert ke excel
df.to_excel("data_berita_clean.xlsx", index=False)
df = pd.read_excel("/content/data_berita_clean.xlsx")

# total jumlah label 0 dan 1
df.head()
df.shape
df['label'].value_counts()

# rata-rata panjang text label 0 dan 1
df['panjang_teks'] = df['final_text'].apply(lambda x: len(x.split()))

df.groupby('label')['panjang_teks'].mean()

# tfidf

X_text = df['final_text']
y = df['label']

tfidf = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1,2)
)

X = tfidf.fit_transform(X_text)

# split data ke train dan test

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# hasil prediksi model

model = MultinomialNB()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

# evaluasi model dengan memprediksi berita baru

def predict_berita(text, tfidf, model):
    text_tfidf = tfidf.transform([text])

    pred = model.predict(text_tfidf)[0]
    prob = model.predict_proba(text_tfidf)[0]

    label = "HOAX" if pred == 1 else "FAKTA"

    return {
        "label_prediksi": label,
        "prob_fakta": prob[0],
        "prob_hoax": prob[1]
    }

berita_baru = """
VIRAL!!! Pemerintah resmi membatalkan Pemilu 2024 dan akan
menunjuk presiden seumur hidup. Informasi ini disembunyikan media.
"""

hasil = predict_berita(berita_baru, tfidf, model)
hasil

berita_baru = """
VIRAL!!! Presiden dibekukan dan diganti AI
"""

hasil = predict_berita(berita_baru, tfidf, model)
hasil

berita_baru = """
Kementerian Pendidikan, Kebudayaan, Riset, dan Teknologi menyampaikan
bahwa pelaksanaan Asesmen Nasional tahun 2023 dilakukan secara daring
dan diikuti oleh satuan pendidikan di seluruh Indonesia.

"""

hasil = predict_berita(berita_baru, tfidf, model)
hasil

berita_baru = """
Badan Pusat Statistik mencatat bahwa tingkat inflasi Indonesia pada
bulan Juni 2023 mengalami penurunan dibandingkan bulan sebelumnya
berdasarkan data resmi yang dirilis.

"""

hasil = predict_berita(berita_baru, tfidf, model)
hasil

# simpan TF-IDF
joblib.dump(tfidf, "tfidf_berita.pkl")

# simpan model Naive Bayes
joblib.dump(model, "model_hoax_nb.pkl")

# menggunakan model untuk website

tfidf_loaded = joblib.load("tfidf_berita.pkl")
model_loaded = joblib.load("model_hoax_nb.pkl")

predict_berita(
    "Pemerintah membatalkan Pemilu 2024",
    tfidf_loaded,
    model_loaded
)