# -*- coding: utf-8 -*-
"""Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B1_ktLUm87Jr6yzO75V3paEZn4KS7kmM
"""

!pip install Sastrawi
import re
import pandas as pd
import numpy as np
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
import ast
from google.colab import files

# Load data
data_hoax = "https://raw.githubusercontent.com/AseLole112/Analisis_Berita_Hoaxs_dan_Fakta/master/dataset_turnbackhoax_10k(hoax).csv"
data_fakta = "https://raw.githubusercontent.com/AseLole112/Analisis_Berita_Hoaxs_dan_Fakta/master/dataset_tempo_6k(fakta).csv"

df_hoax = pd.read_csv(data_hoax, sep=';')
df_fakta = pd.read_csv(data_fakta, sep=';')

# gabungkan data
df = pd.concat([df_hoax, df_fakta], axis=0, ignore_index=True)

df_model_1 = df[['FullText', 'hoax']].copy()
df_model_1.columns = ['text', 'label']

def clean_text(text):
    text = re.sub(r"http\S+|www\S+", "", text)
    text = re.sub(r"[^a-z\s]", " ", text)
    text = re.sub(r"\s+", " ", text)
    text = str(text).lower()
    return text.strip()

df_model_1['text_clean'] = df_model_1['text'].apply(clean_text)
df_model_1['tokens'] = df_model_1['text_clean'].apply(lambda x: x.split())

# Menghapus kata yang tidak bermakna (stopwords) dalam bahasa indonesia
stop_words = set(stopwords.words('indonesian'))

df_model_1['tokens'] = df_model_1['tokens'].apply(
    lambda x: [word for word in x if word not in stop_words]
)

# stemming (mengubah suatu kata menjadi kata dasar)
factory = StemmerFactory()
stemmer = factory.create_stemmer()

df_model_1['tokens'] = df_model_1['tokens'].apply(
    lambda x: [stemmer.stem(word) for word in x]
)

# Menggabungkan kembali tokens menjadi teks
df_model_1['tokens'] = df_model_1['tokens'].apply(ast.literal_eval)
df_model_1['final_text'] = df_model_1['tokens'].apply(lambda x: " ".join(x))

# download clean text
df_model = df_model_1[['final_text', 'label']].copy()

df_final.to_excel("data_clean.xlsx", index=False)
files.download("data_clean.xlsx")