# -*- coding: utf-8 -*-
"""train_hoax.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1osgaiCdKa8apH-xe0dbCX8a6aDAYfRZw
"""

import pandas as pd
from collections import Counter
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt


# Load data
data = "https://raw.githubusercontent.com/AseLole112/Analisis_Berita_Hoaxs_dan_Fakta/master/data_clean.csv"


df = pd.read_csv(data, sep=';')
df[['final_text', 'label']] = df['final_text,label'].str.split(',', n=1, expand=True)
df = df.drop('final_text,label', axis=1)

# hapus null
df = df.dropna(subset=['final_text']).reset_index(drop=True)

# kata paling banyak di text
hoax_words = " ".join(df[df['label'] == 1]['final_text']).split()
fakta_words = " ".join(df[df['label'] == 0]['final_text']).split()
Counter(hoax_words).most_common(20)
Counter(fakta_words).most_common(20)

# converts text into weighted numbers for the AI to process and learn
X_text = df['final_text']
y = df['label']

tfidf = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1,2)
)

X = tfidf.fit_transform(X_text)

# splits the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# trains the Naive Bayes AI using the training data
model = MultinomialNB()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

# cofussion matrix
cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,5))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=['Fakta (0)', 'Hoaks (1)'],
    yticklabels=['Fakta (0)', 'Hoaks (1)']
)
plt.xlabel('Prediksi')
plt.ylabel('Aktual')
plt.title('Confusion Matrix Klasifikasi Berita Hoaks')
plt.show()